### ISSUE TITLE
Missing visible projects

### ISSUE THREAD

**Issue by ralexrdz** [ehecame/vientos-nahual#56] opened 2018-01-19 18:38 UTC
there is a difference in the number of projects showing in between accounts and when loading app in desktop or mobile.
Is not about map zoom.

**Comment by elf-pavlik** [comment] 2018-01-19 19:41
please pay attention to a bug which I introduced - personal filter stays saved in state between reloads but decoration of a button currently doesn't get set properly. sometimes you may have personal filter on but button doesn't show it!

**Comment by ralexrdz** [comment] 2018-01-19 19:53
is not that, I see proposals changing in between state of personal filter on and off, but projects stays in just 2

**Comment by elf-pavlik** [comment] 2018-03-08 19:48
Very likely caused by having some filters enabled and not noticing it, now one can see that some filters stay enabled. Let's close it and see if we encounter that issue again making sure we don't have any filters enabled.

**Closed as completed by elf-pavlik** 2018-03-08 19:48 UTC
Labels: bug
